### ISSUE TITLE
No usb device with vid:0x0fce pid:0xb00b tried bootloader,fastboot,recovery

### ISSUE THREAD

**Issue by ImLoadingUuU** [munjeni/newflasher#62]
It won't detect device even i tried "bootloader","fastboot","recovery" and fastboot devices shows
```
HQ6####### fastboot
```

**Comment by munjeni** [comment]
You must put phone into flash mode (volumeup_power button) while device is shutdown. Connect usb cable while device is shutdown and in the same time keep volumeup+power button, that way your device is in flash mode (blue led in on). Hope this help.

**Comment by ImLoadingUuU** [comment]
tried. My device is XQ-BT52 No usb device with vid:0x0fce pid:0xb00b !

**Comment by munjeni** [comment]
You need to install altest usb driver https://software.sonymobile.com/drivers/installers/latest/Sony_Mobile_Software_Update_Drivers_x64_Setup.msi reboot your pc and try again, newflasher work on tousands of devices and it will work on your device too,

**Comment by ImLoadingUuU** [comment]
In using mac

**Comment by munjeni** [comment]
I can't help on MAC, do it yourself, good luck!

**Comment by munjeni** [comment]
My sugestion try with precompiled newflasher for MAC from here https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/

**Comment by ImLoadingUuU** [comment]
Im using it

**Comment by ImLoadingUuU** [comment]
btw i tried compile newflasher but
```
gcc -Wall -g -O2 -I/usr/local/Cellar/libusb/1.0.23/include/libusb-1.0 newflasher.c -o newflasher -lz -lexpat  -lusb-1.0
newflasher.c:1625:7: warning: variable 'chunk' set but not used [-Wunused-but-set-variable]
                int chunk = 0;
                    ^
newflasher.c:2869:8: error: call to undeclared function 'libusb_get_port_numbers'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        ret = libusb_get_port_numbers(device, port_path, sizeof(port_path));
              ^
newflasher.c:2869:8: note: did you mean 'libusb_get_bus_number'?
./libusb.h:978:21: note: 'libusb_get_bus_number' declared here
uint8_t LIBUSB_CALL libusb_get_bus_number(libusb_device *dev);
                    ^
newflasher.c:2968:56: error: use of undeclared identifier 'LIBUSB_CAP_SUPPORTS_DETACH_KERNEL_DRIVER'
                if ((ret != LIBUSB_SUCCESS) && libusb_has_capability(LIBUSB_CAP_SUPPORTS_DETACH_KERNEL_DRIVER) && (libusb_kernel_driver_active(dev, iface) > 0))
                                                                     ^
1 warning and 2 errors generated.
make: *** [newflasher] Error 1
➜  newflasher-56 
```

**Comment by ImLoadingUuU** [comment]
i think usb device not detected is because some problem with newflasher code. i tried with Parallels Desktop 18, Actual Windows 10 Machine. all no usb device

**Comment by munjeni** [comment]
Parallels Desktop 18 uses the same MAC usb devices, so problem is usb lib you have using while compiling for MAC, you need to find compatibile libusb for newflasher. Which MAC version you have running? Newflasher is fully working on MAC 10.12 and that was first and last one I support, if somebody need for newer MAC fill free and add support for it I simply don't have free time for that and I do not use MAC.
